name: OpenSilver.VSIX Build
env:
  solution-vsix: 'src/VSExtension.OpenSilver.sln'
on:
  # We run the process manually and pass the version
  workflow_dispatch:
    inputs:
      vsix-version:
        description: 'VSIX version'
        default: ''
        required: true
jobs:
  VSIX-Build:
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v1.0.3
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Update Version
        run: |
          $version = "${{ github.event.inputs.vsix-version }}"
          echo "Version: $version"
      - name: Install Visual Studio Build Tools
        run: |
          Install-Module -Scope CurrentUser -Force -Name VisualStudioInstaller
          Import-Module -Name VisualStudioInstaller
          Install-VisualStudio `
            -PackageName 'VisualStudio' `
            -ApplicationName 'Visual Studio Community 2019' `
            -Version '17.8' `
            -Channel 'Release' `
            -Product 'Community' `
            -IncludeRecommended `
            -PassThru `
            -Confirm:$false
      - name: Restore packages
        run: |
          nuget restore ${{ env.solution-vsix }}
      - name: Build solution
        run: |
          msbuild ${{ env.solution-vsix }} -p:Configuration=Release -clp:ErrorsOnly -restore
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OpenSilver.VSIX
          path: "src/OpenSilver.VSIX/bin/OpenSilver/Release/OpenSilver.vsix"